[graph]
all-features = true

[licenses]
allow = ["MIT", "Apache-2.0", "Unicode-3.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "MPL-2.0", "Zlib", "CC0-1.0"]

[bans]
multiple-versions = "warn"
wildcards = "deny"
