[graph]
all-features = true

[licenses]
allow = ["MIT", "Apache-2.0", "Unicode-3.0", "MPL-2.0", "Zlib"]

[bans]
multiple-versions = "warn"
wildcards = "deny"
skip = [{ name = "windows-sys", version = "0.59.0" }]
